### ISSUE TITLE
Unexpected horizontal 'lines'

### ISSUE THREAD

**Issue by pwichmann** [Quasimondo/RasterFairy#24]
**Many thanks for this library, Mario! This effort is much appreciated.**

I am surprised by the results I got today for a little holiday art project I am working on.

The UMAP embeddings for my test case (just the letter 'A' embedded) look like this:
![image](https://github.com/Quasimondo/RasterFairy/assets/13521375/e06767a1-7d05-4ac7-94cd-90f35870669a)

However, after a RasterFairy processing, the grid image shows **horizontal stripes**, here a small section (but along the full width of the image):
![image](https://github.com/Quasimondo/RasterFairy/assets/13521375/08a179bb-bbf0-46bf-be7b-73a837ca0b72)

What is the cause of these horizontal stripes? Are there libraries that prevent these from occurring (note that these stripes are not present in the original UMAP embeddings). I would expected 2D blobs of similar images, just like in the demo animation in this repo.

**Comment by Quasimondo** [comment]
You might want to try a different proportion for your grid and see if the result looks better. You could also try to pre-rotate the umap coordinates and see if that changes the outcome. Sometimes there are cases where RasteFairy does not give you the visually optimal result.

It's hard to tell from dots in umap whether those A's that look stripey actually lie on the outer edges of those clusters. S

**Comment by pwichmann** [comment]
Wow, thanks, Mario.

I tried with a different aspect ratio. This was a good idea.

Again, however, I get some artefacts but this time I get three vertical stripes.
The problem is that if you move one letter to the right and thereby cross the boundary between two vertical stripes, you suddenly jump to letters that are very dissimilar.

![image](https://github.com/Quasimondo/RasterFairy/assets/13521375/2d8d909e-d2dc-4c63-927d-a1c84fa42e36)

**Comment by pwichmann** [comment]
Here, zoomed in onto the border between two vertical stripes:

![image](https://github.com/Quasimondo/RasterFairy/assets/13521375/3c055c9e-b43c-4a31-8e70-8d385c346fe3)

This is likely not intended behaviour, I guess.

**Comment by pwichmann** [comment]
Using t-sne, the effect is gone. So I close this issue. I only had it with UMAP positions.
