### ISSUE TITLE
How to label data?

### ISSUE THREAD

**Issue by jeffThompson** [Quasimondo/RasterFairy#6]
Not exactly an issue, more of a question that I can't figure out from your demos: when running `transformPointCloud2D()` does the order of points in the array stay the same as the original? In other words, if I have a numpy array of my data and another with labels, will they still correlate after the transformation?

**Comment by jeffThompson** [comment]
PS – thanks for this very useful, intuitive code!

**Comment by Quasimondo** [comment]
Yes, the order of the points stays the same. Only if you use the rfoptimizer to further improve the arrangement it will change, but then the rfoptimizer returns a LUT that allows you to map the old indices to the new ones.

**Comment by jeffThompson** [comment]
Super, I figured but couldn't find it in the docs. Thanks!

**Comment by Quasimondo** [comment]
Which docs ;-)?
